# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\designs\FAS.ui'
#
# Created: Sat Nov 24 16:18:03 2018
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_FAS(object):
    def setupUi(self, FAS):
        FAS.setObjectName(_fromUtf8("FAS"))
        FAS.resize(962, 774)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../favicon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        FAS.setWindowIcon(icon)
        FAS.setStyleSheet(_fromUtf8(""))
        self.gridLayout = QtGui.QGridLayout(FAS)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtGui.QLabel(FAS)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setScaledContents(False)
        self.label.setWordWrap(False)
        self.label.setMargin(32)
        self.label.setIndent(-1)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.tab_4 = QtGui.QTabWidget(FAS)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.tab_4.setFont(font)
        self.tab_4.setStyleSheet(_fromUtf8(""))
        self.tab_4.setDocumentMode(False)
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.add_class_tab = QtGui.QWidget()
        self.add_class_tab.setObjectName(_fromUtf8("add_class_tab"))
        self.gridLayout_8 = QtGui.QGridLayout(self.add_class_tab)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem2, 0, 2, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.add_class_tab)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_25 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_25.setObjectName(_fromUtf8("verticalLayout_25"))
        self.formLayout_13 = QtGui.QFormLayout()
        self.formLayout_13.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_13.setObjectName(_fromUtf8("formLayout_13"))
        self.label_24 = QtGui.QLabel(self.groupBox_5)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.formLayout_13.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_24)
        self.add_class_no = QtGui.QLineEdit(self.groupBox_5)
        self.add_class_no.setObjectName(_fromUtf8("add_class_no"))
        self.formLayout_13.setWidget(0, QtGui.QFormLayout.FieldRole, self.add_class_no)
        self.label_25 = QtGui.QLabel(self.groupBox_5)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.formLayout_13.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_25)
        self.add_class_teacher = QtGui.QLineEdit(self.groupBox_5)
        self.add_class_teacher.setObjectName(_fromUtf8("add_class_teacher"))
        self.formLayout_13.setWidget(1, QtGui.QFormLayout.FieldRole, self.add_class_teacher)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem3)
        self.add_class_btn = QtGui.QPushButton(self.groupBox_5)
        self.add_class_btn.setObjectName(_fromUtf8("add_class_btn"))
        self.horizontalLayout_15.addWidget(self.add_class_btn)
        self.formLayout_13.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout_15)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout_13.setItem(3, QtGui.QFormLayout.FieldRole, spacerItem4)
        self.label_23 = QtGui.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.formLayout_13.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_23)
        self.add_class_status = QtGui.QLabel(self.groupBox_5)
        self.add_class_status.setObjectName(_fromUtf8("add_class_status"))
        self.formLayout_13.setWidget(5, QtGui.QFormLayout.LabelRole, self.add_class_status)
        self.verticalLayout_25.addLayout(self.formLayout_13)
        self.gridLayout_8.addWidget(self.groupBox_5, 0, 1, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem5, 1, 1, 1, 1)
        self.tab_4.addTab(self.add_class_tab, _fromUtf8(""))
        self.register_tab = QtGui.QWidget()
        self.register_tab.setObjectName(_fromUtf8("register_tab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.register_tab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.register_tab)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.register_student_pic = QtGui.QLabel(self.groupBox)
        self.register_student_pic.setText(_fromUtf8(""))
        self.register_student_pic.setPixmap(QtGui.QPixmap(_fromUtf8(":/holder/img/holder_1.PNG")))
        self.register_student_pic.setObjectName(_fromUtf8("register_student_pic"))
        self.verticalLayout_3.addWidget(self.register_student_pic)
        self.reg_std_upload_btn = QtGui.QPushButton(self.groupBox)
        self.reg_std_upload_btn.setObjectName(_fromUtf8("reg_std_upload_btn"))
        self.verticalLayout_3.addWidget(self.reg_std_upload_btn)
        self.reg_std_add_finger_btn = QtGui.QPushButton(self.groupBox)
        self.reg_std_add_finger_btn.setObjectName(_fromUtf8("reg_std_add_finger_btn"))
        self.verticalLayout_3.addWidget(self.reg_std_add_finger_btn)
        self.formLayout_14 = QtGui.QFormLayout()
        self.formLayout_14.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_14.setObjectName(_fromUtf8("formLayout_14"))
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout_14.setItem(0, QtGui.QFormLayout.LabelRole, spacerItem6)
        self.label_6 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_14.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.reg_std_status = QtGui.QLabel(self.groupBox)
        self.reg_std_status.setObjectName(_fromUtf8("reg_std_status"))
        self.formLayout_14.setWidget(2, QtGui.QFormLayout.LabelRole, self.reg_std_status)
        self.verticalLayout_3.addLayout(self.formLayout_14)
        self.gridLayout_4.addLayout(self.verticalLayout_3, 1, 3, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem7, 1, 4, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem8, 4, 6, 1, 1)
        self.formLayout_6 = QtGui.QFormLayout()
        self.formLayout_6.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.reg_std_id = QtGui.QLineEdit(self.groupBox)
        self.reg_std_id.setObjectName(_fromUtf8("reg_std_id"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.FieldRole, self.reg_std_id)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.reg_std_name = QtGui.QLineEdit(self.groupBox)
        self.reg_std_name.setObjectName(_fromUtf8("reg_std_name"))
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.FieldRole, self.reg_std_name)
        self.label_14 = QtGui.QLabel(self.groupBox)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout_6.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_14)
        self.reg_std_dob = QtGui.QDateEdit(self.groupBox)
        self.reg_std_dob.setObjectName(_fromUtf8("reg_std_dob"))
        self.formLayout_6.setWidget(3, QtGui.QFormLayout.FieldRole, self.reg_std_dob)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_6.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_4)
        self.reg_std_guardian = QtGui.QLineEdit(self.groupBox)
        self.reg_std_guardian.setObjectName(_fromUtf8("reg_std_guardian"))
        self.formLayout_6.setWidget(4, QtGui.QFormLayout.FieldRole, self.reg_std_guardian)
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_6.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_8)
        self.reg_std_class = QtGui.QComboBox(self.groupBox)
        self.reg_std_class.setObjectName(_fromUtf8("reg_std_class"))
        self.formLayout_6.setWidget(5, QtGui.QFormLayout.FieldRole, self.reg_std_class)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_6.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_5)
        self.reg_std_address = QtGui.QTextEdit(self.groupBox)
        self.reg_std_address.setObjectName(_fromUtf8("reg_std_address"))
        self.formLayout_6.setWidget(6, QtGui.QFormLayout.FieldRole, self.reg_std_address)
        self.reg_std_btn = QtGui.QPushButton(self.groupBox)
        self.reg_std_btn.setObjectName(_fromUtf8("reg_std_btn"))
        self.formLayout_6.setWidget(8, QtGui.QFormLayout.FieldRole, self.reg_std_btn)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout_6.setItem(7, QtGui.QFormLayout.FieldRole, spacerItem9)
        self.gridLayout_4.addLayout(self.formLayout_6, 1, 5, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem10, 4, 3, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem11, 4, 1, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem12, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.tab_4.addTab(self.register_tab, _fromUtf8(""))
        self.records_tab = QtGui.QWidget()
        self.records_tab.setObjectName(_fromUtf8("records_tab"))
        self.gridLayout_6 = QtGui.QGridLayout(self.records_tab)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.verticalLayout_24 = QtGui.QVBoxLayout()
        self.verticalLayout_24.setObjectName(_fromUtf8("verticalLayout_24"))
        self.groupBox_4 = QtGui.QGroupBox(self.records_tab)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.formLayout_12 = QtGui.QFormLayout(self.groupBox_4)
        self.formLayout_12.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_12.setObjectName(_fromUtf8("formLayout_12"))
        self.label_18 = QtGui.QLabel(self.groupBox_4)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.formLayout_12.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_18)
        self.res_class = QtGui.QComboBox(self.groupBox_4)
        self.res_class.setObjectName(_fromUtf8("res_class"))
        self.formLayout_12.setWidget(0, QtGui.QFormLayout.FieldRole, self.res_class)
        self.label_21 = QtGui.QLabel(self.groupBox_4)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.formLayout_12.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_21)
        self.res_teacher = QtGui.QLineEdit(self.groupBox_4)
        self.res_teacher.setObjectName(_fromUtf8("res_teacher"))
        self.formLayout_12.setWidget(1, QtGui.QFormLayout.FieldRole, self.res_teacher)
        self.label_19 = QtGui.QLabel(self.groupBox_4)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.formLayout_12.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_19)
        self.res_date_from = QtGui.QDateEdit(self.groupBox_4)
        self.res_date_from.setObjectName(_fromUtf8("res_date_from"))
        self.formLayout_12.setWidget(2, QtGui.QFormLayout.FieldRole, self.res_date_from)
        self.label_20 = QtGui.QLabel(self.groupBox_4)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.formLayout_12.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_20)
        self.res_date_to = QtGui.QDateEdit(self.groupBox_4)
        self.res_date_to.setObjectName(_fromUtf8("res_date_to"))
        self.formLayout_12.setWidget(3, QtGui.QFormLayout.FieldRole, self.res_date_to)
        self.verticalLayout_24.addWidget(self.groupBox_4)
        self.frame_2 = QtGui.QFrame(self.records_tab)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_24.addWidget(self.frame_2)
        self.horizontalLayout_13.addLayout(self.verticalLayout_24)
        self.verticalLayout_23 = QtGui.QVBoxLayout()
        self.verticalLayout_23.setObjectName(_fromUtf8("verticalLayout_23"))
        self.label_22 = QtGui.QLabel(self.records_tab)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.verticalLayout_23.addWidget(self.label_22)
        self.result_view = QtGui.QTableView(self.records_tab)
        self.result_view.setStyleSheet(_fromUtf8("background-color: rgb(231, 231, 231);"))
        self.result_view.setObjectName(_fromUtf8("result_view"))
        self.verticalLayout_23.addWidget(self.result_view)
        self.horizontalLayout_13.addLayout(self.verticalLayout_23)
        self.gridLayout_6.addLayout(self.horizontalLayout_13, 0, 1, 1, 1)
        self.tab_4.addTab(self.records_tab, _fromUtf8(""))
        self.gridLayout.addWidget(self.tab_4, 2, 0, 1, 1)

        self.retranslateUi(FAS)
        self.tab_4.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(FAS)

    def retranslateUi(self, FAS):
        FAS.setWindowTitle(_translate("FAS", "Fingerprint Attendance (Admin)", None))
        self.label.setText(_translate("FAS", "Fingerprint Based Attendance System", None))
        self.groupBox_5.setTitle(_translate("FAS", "GroupBox", None))
        self.label_24.setText(_translate("FAS", "Class No", None))
        self.label_25.setText(_translate("FAS", "Teacher Name", None))
        self.add_class_btn.setText(_translate("FAS", "Add Class", None))
        self.label_23.setText(_translate("FAS", "Status ", None))
        self.add_class_status.setText(_translate("FAS", "....", None))
        self.tab_4.setTabText(self.tab_4.indexOf(self.add_class_tab), _translate("FAS", "Add Class", None))
        self.groupBox.setTitle(_translate("FAS", "Student Details", None))
        self.reg_std_upload_btn.setText(_translate("FAS", "Upload Image", None))
        self.reg_std_add_finger_btn.setText(_translate("FAS", "Add Fingerprint", None))
        self.label_6.setText(_translate("FAS", "Status ", None))
        self.reg_std_status.setText(_translate("FAS", "Please add Fingerprint", None))
        self.label_2.setText(_translate("FAS", "Student ID", None))
        self.label_3.setText(_translate("FAS", "Name", None))
        self.label_14.setText(_translate("FAS", "DOB", None))
        self.label_4.setText(_translate("FAS", "Guardian ", None))
        self.label_8.setText(_translate("FAS", "Class", None))
        self.label_5.setText(_translate("FAS", "Address", None))
        self.reg_std_btn.setText(_translate("FAS", "Register", None))
        self.tab_4.setTabText(self.tab_4.indexOf(self.register_tab), _translate("FAS", "Register", None))
        self.groupBox_4.setTitle(_translate("FAS", "GroupBox", None))
        self.label_18.setText(_translate("FAS", "Class", None))
        self.label_21.setText(_translate("FAS", "Teacher", None))
        self.label_19.setText(_translate("FAS", "From", None))
        self.label_20.setText(_translate("FAS", "To", None))
        self.label_22.setText(_translate("FAS", "Attendance Results", None))
        self.tab_4.setTabText(self.tab_4.indexOf(self.records_tab), _translate("FAS", "Display Record", None))

import resource_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    FAS = QtGui.QWidget()
    ui = Ui_FAS()
    ui.setupUi(FAS)
    FAS.show()
    sys.exit(app.exec_())

