# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\designs\FAS_attendance.ui'
#
# Created: Sat Nov 24 16:17:32 2018
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1007, 787)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../../favicon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setMargin(32)
        self.label.setIndent(14)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.attendance_tab = QtGui.QTabWidget(self.centralwidget)
        self.attendance_tab.setObjectName(_fromUtf8("attendance_tab"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayout = QtGui.QFormLayout(self.groupBox)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.scan_class_no = QtGui.QComboBox(self.groupBox)
        self.scan_class_no.setObjectName(_fromUtf8("scan_class_no"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.scan_class_no)
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_8)
        self.scan_teacher = QtGui.QLineEdit(self.groupBox)
        self.scan_teacher.setObjectName(_fromUtf8("scan_teacher"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.scan_teacher)
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_9)
        self.scan_date = QtGui.QLineEdit(self.groupBox)
        self.scan_date.setObjectName(_fromUtf8("scan_date"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.scan_date)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        self.groupBox_3 = QtGui.QGroupBox(self.tab)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_11 = QtGui.QLabel(self.groupBox_3)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_11)
        self.scan_status = QtGui.QLabel(self.groupBox_3)
        self.scan_status.setObjectName(_fromUtf8("scan_status"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.scan_status)
        self.verticalLayout_6.addLayout(self.formLayout_3)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.scan_done_btn = QtGui.QPushButton(self.groupBox_3)
        self.scan_done_btn.setObjectName(_fromUtf8("scan_done_btn"))
        self.gridLayout_4.addWidget(self.scan_done_btn, 1, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem2, 0, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 1, 0, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_4)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox_2)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.scan_std_pic = QtGui.QLabel(self.groupBox_2)
        self.scan_std_pic.setText(_fromUtf8(""))
        self.scan_std_pic.setPixmap(QtGui.QPixmap(_fromUtf8(":/holder/img/holder_1.PNG")))
        self.scan_std_pic.setObjectName(_fromUtf8("scan_std_pic"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.scan_std_pic)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout_2.setItem(2, QtGui.QFormLayout.LabelRole, spacerItem4)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.scan_std_id = QtGui.QLineEdit(self.groupBox_2)
        self.scan_std_id.setEnabled(False)
        self.scan_std_id.setObjectName(_fromUtf8("scan_std_id"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.scan_std_id)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_5)
        self.scan_std_name = QtGui.QLineEdit(self.groupBox_2)
        self.scan_std_name.setEnabled(False)
        self.scan_std_name.setObjectName(_fromUtf8("scan_std_name"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.scan_std_name)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_6)
        self.scan_std_dob = QtGui.QLineEdit(self.groupBox_2)
        self.scan_std_dob.setEnabled(False)
        self.scan_std_dob.setObjectName(_fromUtf8("scan_std_dob"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.scan_std_dob)
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_7)
        self.scan_std_guardian = QtGui.QLineEdit(self.groupBox_2)
        self.scan_std_guardian.setEnabled(False)
        self.scan_std_guardian.setObjectName(_fromUtf8("scan_std_guardian"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.FieldRole, self.scan_std_guardian)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout_2.setItem(7, QtGui.QFormLayout.FieldRole, spacerItem5)
        self.scan_finger_btn = QtGui.QPushButton(self.groupBox_2)
        self.scan_finger_btn.setObjectName(_fromUtf8("scan_finger_btn"))
        self.formLayout_2.setWidget(8, QtGui.QFormLayout.FieldRole, self.scan_finger_btn)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.attendance_tab.addTab(self.tab, _fromUtf8(""))
        self.gridLayout.addWidget(self.attendance_tab, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.attendance_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Fingerprint Attendance (Student)", None))
        self.label.setText(_translate("MainWindow", "Fingerprint Based Attendance System", None))
        self.groupBox.setTitle(_translate("MainWindow", "Class Details", None))
        self.label_2.setText(_translate("MainWindow", "Class", None))
        self.label_8.setText(_translate("MainWindow", "Teacher", None))
        self.label_9.setText(_translate("MainWindow", "Date", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Info", None))
        self.label_11.setText(_translate("MainWindow", "Status:", None))
        self.scan_status.setText(_translate("MainWindow", "Please click \"Done\" to finalise your attendance", None))
        self.scan_done_btn.setText(_translate("MainWindow", "Done", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Student Details", None))
        self.label_4.setText(_translate("MainWindow", "Student ID", None))
        self.label_5.setText(_translate("MainWindow", "Name", None))
        self.label_6.setText(_translate("MainWindow", "DOB", None))
        self.label_7.setText(_translate("MainWindow", "Guardian", None))
        self.scan_finger_btn.setText(_translate("MainWindow", "Scan Fingerprint", None))
        self.attendance_tab.setTabText(self.attendance_tab.indexOf(self.tab), _translate("MainWindow", "Attendance", None))

import resource_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

